# This workflow checks that windows paths (a\b\c) work correctly when passed as args to taskipy

name: Taskipy Windows Sanity Test

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: Test Windows-Style Paths
      run: poetry run task run_unittest_as_windows_sanity tests\test_windows_sanity.py
